import fs from 'node:fs';
import { baseName } from '../model.js';

export const START = '<!-- unstuck:start -->';
export const END = '<!-- unstuck:end -->';

/**
 * Turn cross-session patterns into reviewable AGENTS.md / CLAUDE.md lines.
 * Every line states its evidence so the reader can judge it.
 * @param {import('../scan.js').ScanResult} result
 * @returns {string[]} bullet lines (empty if nothing recurred)
 */
export function suggestionLines(result) {
  const { learnedFixes, repeatedCorrections, outputHogs, hotFiles } = result.patterns;
  const lines = [];
  for (const f of learnedFixes.slice(0, 8)) {
    const why = f.error ? ` (\`${f.failed.split(' ')[0]}\` failed: ${f.error.replace(/`/g, "'")})` : '';
    lines.push(`- Run \`${f.worked}\` instead of \`${f.failed}\`${why}. Seen ${f.count}× in ${f.sessions} session${f.sessions === 1 ? '' : 's'}.`);
  }
  for (const r of repeatedCorrections.slice(0, 5)) {
    lines.push(`- Rule candidate: "${r.text.replace(/"/g, "'")}" (you said this ${r.count}×).`);
  }
  for (const h of outputHogs.filter((x) => x.tokens >= 3000).slice(0, 3)) {
    lines.push(`- \`${h.command}\` prints a lot (~${Math.round(h.tokens / 1000)}k tokens over ${h.calls} call${h.calls === 1 ? '' : 's'}). Prefer a quiet flag or pipe through \`tail -n 40\`.`);
  }
  if (hotFiles.length) {
    const names = hotFiles.slice(0, 5).map((f) => `\`${f.file}\``).join(', ');
    lines.push(`- Files the agent re-discovers in most sessions: ${names}. Add one line each saying what they are.`);
  }
  return lines;
}

/** @param {import('../scan.js').ScanResult} result */
export function renderSuggest(result) {
  const lines = suggestionLines(result);
  if (lines.length === 0) {
    return 'Nothing recurred across sessions yet, so there is nothing worth adding to AGENTS.md.\nTry a wider window (--since 90d) or come back after a few more sessions.\n';
  }
  return [
    START,
    '## Learned from past agent sessions',
    '',
    '<!-- Generated by unstuck from local session logs. Review each line before keeping it. -->',
    ...lines,
    END,
    '',
  ].join('\n');
}

/**
 * Insert or replace the unstuck block in a markdown file. Idempotent.
 * @param {string} file
 * @param {string} block output of renderSuggest
 */
export function appendBlock(file, block) {
  const body = block.trimEnd();
  let text = '';
  try {
    text = fs.readFileSync(file, 'utf8');
  } catch {
    /* new file */
  }
  const a = text.indexOf(START);
  const b = text.indexOf(END);
  if (a !== -1 && b > a) {
    text = `${text.slice(0, a)}${body}${text.slice(b + END.length)}`;
  } else {
    text = `${text.trimEnd()}${text.trim() ? '\n\n' : ''}${body}\n`;
  }
  fs.writeFileSync(file, text.endsWith('\n') ? text : `${text}\n`);
  return baseName(file);
}
